export default {
    colors: {
        // primary: '#5AB198',
        primary: '#5CB15A',
        secondary: '#5AB198',
        error: '#E54D4D',
        red: '#FF0000',
        gray: '#D4D4D4',
        grayOpacity: '#D4D4D4DC',
        lightGray: '#F2F2F2',
        white: '#FFFFFF',
        ice: '#E5E5E5E5',
        black: '#000000',
        lightBlack: '#666',
        regular: '#999',
        placeholder: '#B9B9B9',
        softPlaceholder: '#AAA',
        background: '#A8DBD9',
        transparent: 'transparent',
        darkTransparent: 'rgba(0, 0, 0, 0.6)',
    },
    fonts: {
        regular: 'Inter-Regular',
        bold: 'Inter-Bold',
        extraBold: 'Inter-ExtraBold',
        extraLight: 'Inter-ExtraLight',
        light: 'Inter-Light',
        medium: 'Inter-Medium',
        semiBold: 'Inter-SemiBold',
        thin: 'Inter-Thin',

        size: {
            xsmall: '10px',
            small: '12px',
            medium: '16px',
            large: '20px',
            xlarge: '24px',
            xxlarge: '28px',
            xxxlarge: '32px',
        },
    },
};
